version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.4.4
    container_name: es01
    networks:
      - elastic
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
    mem_limit: 1GB
    volumes:
      - "/data/es01:/usr/share/elasticsearch/data" # Mount the data volume
networks:
  elastic:
    driver: bridge
