---
- name: reload sysctl
  ansible.builtin.command: service procps force-reload
  ignore_errors: true

- name: Restart Chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
  ignore_errors: true

- name: Restart Sysstat
  ansible.builtin.service:
    name: sysstat
    state: restarted
  ignore_errors: true

- name: Restart Rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  ignore_errors: true

- name: Restart Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  ignore_errors: true

- name: Reload Auditd Rules
  ansible.builtin.command: augenrules --load
  ignore_errors: true

- name: Restart Unattended-Upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
  ignore_errors: true

- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  ignore_errors: true
