#!/usr/bin/env bats
#
# Regression tests for the "# Python caches" block added to .gitignore,
# which ensures compiled Python bytecode caches (__pycache__/ directories
# and *.pyc files) generated by scripts/mkdocs_hooks.py are never
# accidentally tracked or committed to the repository.

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
GITIGNORE="${REPO_ROOT}/.gitignore"

setup() {
  TEST_TMPDIR="$(mktemp -d)"
  git init -q "${TEST_TMPDIR}"
  cp "${GITIGNORE}" "${TEST_TMPDIR}/.gitignore"
}

teardown() {
  rm -rf "${TEST_TMPDIR}"
}

@test ".gitignore declares a 'Python caches' section" {
  grep -qF -- '# Python caches' "${GITIGNORE}"
}

@test ".gitignore contains the __pycache__/ and *.pyc patterns" {
  grep -qF -- '__pycache__/' "${GITIGNORE}"
  grep -qF -- '*.pyc' "${GITIGNORE}"
}

@test ".gitignore retains the pre-existing credentials/secrets block (no accidental truncation)" {
  grep -qF -- '# Credentials and secrets' "${GITIGNORE}"
  grep -qF -- '*.env' "${GITIGNORE}"
  grep -qF -- '*.vault' "${GITIGNORE}"
}

@test ".gitignore: the Python caches block appears after the credentials/secrets block" {
  local creds_line pycache_line
  creds_line="$(grep -n -F '# Credentials and secrets' "${GITIGNORE}" | head -1 | cut -d: -f1)"
  pycache_line="$(grep -n -F '# Python caches' "${GITIGNORE}" | head -1 | cut -d: -f1)"
  [ -n "${creds_line}" ]
  [ -n "${pycache_line}" ]
  [ "${pycache_line}" -gt "${creds_line}" ]
}

@test "git actually ignores __pycache__ directories" {
  mkdir -p "${TEST_TMPDIR}/scripts/__pycache__"
  touch "${TEST_TMPDIR}/scripts/__pycache__/mkdocs_hooks.cpython-39.pyc"
  run git -C "${TEST_TMPDIR}" check-ignore -q "scripts/__pycache__"
  [ "${status}" -eq 0 ]
}

@test "git actually ignores *.pyc files regardless of directory depth" {
  mkdir -p "${TEST_TMPDIR}/scripts"
  touch "${TEST_TMPDIR}/scripts/mkdocs_hooks.pyc"
  run git -C "${TEST_TMPDIR}" check-ignore -q "scripts/mkdocs_hooks.pyc"
  [ "${status}" -eq 0 ]
}

@test "git status does not report __pycache__ contents or .pyc files as untracked" {
  mkdir -p "${TEST_TMPDIR}/__pycache__"
  touch "${TEST_TMPDIR}/__pycache__/mod.cpython-39.pyc" "${TEST_TMPDIR}/top.pyc"
  porcelain="$(cd "${TEST_TMPDIR}" && git status --porcelain)"
  [[ "${porcelain}" != *"__pycache__"* ]]
  [[ "${porcelain}" != *"top.pyc"* ]]
}

@test "git does NOT ignore unrelated Python source files (*.py)" {
  touch "${TEST_TMPDIR}/mkdocs_hooks.py"
  run git -C "${TEST_TMPDIR}" check-ignore -q "mkdocs_hooks.py"
  [ "${status}" -ne 0 ]
}