#!/usr/bin/env bats
# File: test-scripts/test_elasticsearch_sh.bats
# Description: Tests for test-scripts/test-elasticsearch.sh, which replaced
# a hardcoded ESPASSWORD value with a password sourced from either the
# ESPASSWORD environment variable or the shared temp_credentials.txt file
# generated by the ansible/setup_elasticsearch.yml playbook.
#
# The script invokes curl via its hardcoded absolute path (/usr/bin/curl),
# so PATH-based stubbing alone cannot intercept it. Tests that need to
# inspect the curl invocation instead run a harness copy of the script with
# that absolute path rewritten (via sed) to point at a stub executable,
# mirroring the substitution technique already used in
# test-scripts/setup_step1_install.bats and setup_wait_for_container.bats.
# Tests that only exercise the early-exit/error path (before curl would
# ever be invoked) run the real, unmodified script directly.

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
SCRIPT="${REPO_ROOT}/test-scripts/test-elasticsearch.sh"

setup() {
  TEST_TMPDIR="$(mktemp -d)"
  STUB_BIN="${TEST_TMPDIR}/bin"
  mkdir -p "${STUB_BIN}"
  CALL_LOG="${TEST_TMPDIR}/calls.log"
  : > "${CALL_LOG}"

  # Stub curl so no real network call is ever made; it just records how it
  # was invoked.
  cat > "${STUB_BIN}/curl" <<EOF
#!/usr/bin/env bash
echo "curl \$*" >> "${CALL_LOG}"
exit 0
EOF
  chmod +x "${STUB_BIN}/curl"
  export PATH="${STUB_BIN}:${PATH}"
}

teardown() {
  rm -rf "${TEST_TMPDIR}"
}

# Builds a harness copy of the real script with the hardcoded
# "/usr/bin/curl" invocation rewritten to point at our stub curl, so the
# curl invocation can be inspected without touching the real /usr/bin/curl.
build_harness() {
  local harness="${TEST_TMPDIR}/harness_$$_${RANDOM}.sh"
  sed "s#/usr/bin/curl#${STUB_BIN}/curl#" "${SCRIPT}" > "${harness}"
  chmod +x "${harness}"
  echo "${harness}"
}

@test "test-elasticsearch.sh exists, is readable, and has valid bash syntax" {
  [ -f "${SCRIPT}" ]
  [ -r "${SCRIPT}" ]
  run bash -n "${SCRIPT}"
  [ "${status}" -eq 0 ]
}

@test "test-elasticsearch.sh no longer hardcodes the old leaked ESPASSWORD value" {
  run grep -F 'MMKG16a7=pSOs0TzR87l' "${SCRIPT}"
  [ "${status}" -ne 0 ]
}

@test "test-elasticsearch.sh no longer contains a hardcoded ESPASSWORD= literal assignment" {
  run grep -E '^ESPASSWORD="[^$]' "${SCRIPT}"
  [ "${status}" -ne 0 ]
}

@test "test-elasticsearch.sh invokes curl via its absolute path (sanity check for the harness substitution below)" {
  run grep -F '/usr/bin/curl --cacert' "${SCRIPT}"
  [ "${status}" -eq 0 ]
}

@test "fails with a helpful error and exit code 1 when ESPASSWORD is unset and no credentials file exists" {
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${TEST_TMPDIR}/does-not-exist.txt" bash "${SCRIPT}"
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"Error: ESPASSWORD is not set and could not be found in"* ]]
  [[ "${output}" == *"Usage: ESPASSWORD='your_password'"* ]]
}

@test "a credentials file present but missing a matching password line still triggers the missing-ESPASSWORD error" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo "some unrelated content, no password line here" > "${creds}"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" bash "${SCRIPT}"
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"Error: ESPASSWORD is not set"* ]]
}

@test "computes the default TEMP_CREDENTIALS_FILE relative to the script's own directory" {
  run grep -F 'TEMP_CREDENTIALS_FILE="${TEMP_CREDENTIALS_FILE:-${SCRIPT_DIR}/../elk-wolfi/temp_credentials.txt}"' "${SCRIPT}"
  [ "${status}" -eq 0 ]
}

@test "uses ESPASSWORD from the environment directly, without needing a credentials file" {
  harness="$(build_harness)"
  run env ESPASSWORD="env-password-123" TEMP_CREDENTIALS_FILE="${TEST_TMPDIR}/does-not-exist.txt" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "-u elastic:env-password-123" "${CALL_LOG}"
}

@test "reads the password from the credentials file when ESPASSWORD is not set" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  cat > "${creds}" <<'EOF'
--- Step 6: Retrieve and Store Elasticsearch Password ---
2024-01-01T00:00:00Z
Elastic password set to: FileBasedPass456
EOF
  harness="$(build_harness)"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "-u elastic:FileBasedPass456" "${CALL_LOG}"
}

@test "strips surrounding whitespace from the password extracted from the credentials file" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  printf 'Elastic password set to:   SpaceyPass789   \n' > "${creds}"
  harness="$(build_harness)"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "-u elastic:SpaceyPass789" "${CALL_LOG}"
}

@test "an explicit ESPASSWORD environment variable takes precedence over the credentials file" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo "Elastic password set to: FromFile" > "${creds}"
  harness="$(build_harness)"
  run env ESPASSWORD="FromEnv" TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "-u elastic:FromEnv" "${CALL_LOG}"
  run grep -qF "FromFile" "${CALL_LOG}"
  [ "${status}" -ne 0 ]
}

@test "uses the documented default CERT_PATH when CERT_PATH is not overridden" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo "Elastic password set to: Pass1" > "${creds}"
  harness="$(build_harness)"
  run env -u ESPASSWORD -u CERT_PATH TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "--cacert /root/elastic_stack/podman-elastic-stack/elk-wolfi/certs/http_ca.crt" "${CALL_LOG}"
}

@test "honors a custom CERT_PATH override" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo "Elastic password set to: Pass1" > "${creds}"
  harness="$(build_harness)"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" CERT_PATH="/custom/ca.crt" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- "--cacert /custom/ca.crt" "${CALL_LOG}"
}

@test "calls curl against https://localhost:9200 exactly once on success" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo "Elastic password set to: Pass1" > "${creds}"
  harness="$(build_harness)"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  [ "$(grep -c 'https://localhost:9200' "${CALL_LOG}")" -eq 1 ]
  [ "$(wc -l < "${CALL_LOG}")" -eq 1 ]
}

@test "passwords containing special shell characters are passed through to curl intact" {
  creds="${TEST_TMPDIR}/temp_credentials.txt"
  echo 'Elastic password set to: p@ss$w0rd!#123' > "${creds}"
  harness="$(build_harness)"
  run env -u ESPASSWORD TEMP_CREDENTIALS_FILE="${creds}" bash "${harness}"
  [ "${status}" -eq 0 ]
  grep -qF -- '-u elastic:p@ss$w0rd!#123' "${CALL_LOG}"
}